# Generated by Django 2.2.1 on 2019-09-10 20:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['date'], 'verbose_name': 'article'},
        ),
        migrations.AddField(
            model_name='article',
            name='auteur',
            field=models.CharField(default='Anonyme', max_length=42),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='contenu',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de parution'),
        ),
    ]
